imageTests+=(
	[nginx]='
        ipv6
        static
        templates
        templates-resolver
        templates-resolver-ipv6
        workers
        modules
	'
    [nginxinc/nginx-unprivileged]='
        ipv6
        static
        templates
        templates-resolver
        templates-resolver-ipv6
        workers
        modules
    '
)
